# Generated by Django 4.2.9 on 2025-02-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itServ', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userr',
        ),
    ]
