# Generated by Django 4.2.9 on 2025-03-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itServ', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
