# Generated by Django 4.2.9 on 2025-03-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itServ', '0004_profil_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='first_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='last_authentication',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
