# Generated by Django 4.2.9 on 2025-03-10 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itServ', '0009_conge_typeconge_delete_leaverequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='type_conge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests', to='itServ.typeconge'),
        ),
    ]
