# Generated by Django 4.2.9 on 2025-03-22 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itServ', '0013_typeabsence_remove_absence_type_conge_absence_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absence',
            name='image',
        ),
        migrations.AlterField(
            model_name='absence',
            name='type_absence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itServ.typeabsence'),
        ),
        migrations.DeleteModel(
            name='Absences',
        ),
    ]
