# Generated by Django 4.2.9 on 2025-03-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itServ', '0015_pointage'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='absence_images/'),
        ),
    ]
