# Generated by Django 4.2.9 on 2025-04-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itServ', '0018_leavepreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conge',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Refusé', 'Refusé'), ('planned', 'Planifié')], default='En attente', max_length=20),
        ),
    ]
