# Generated by Django 4.2.9 on 2025-04-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itServ', '0019_alter_conge_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rayon_m', models.FloatField(default=100)),
            ],
        ),
        migrations.AddField(
            model_name='pointage',
            name='est_valide',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointage',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
