# Generated by Django 4.2.9 on 2025-04-16 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itServ', '0020_societe_pointage_est_valide_pointage_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='societe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='itServ.societe'),
        ),
    ]
