# Generated by Django 4.2.9 on 2025-04-21 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itServ', '0021_pointage_societe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='societe',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='rayon_m',
        ),
        migrations.AddField(
            model_name='societe',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='societe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 21, 23, 20, 32, 328263, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='societe',
            name='location_societe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='societe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
