# Generated by Django 4.2.9 on 2025-04-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itServ', '0022_remove_societe_latitude_remove_societe_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='societe',
            name='rayon_acceptable',
            field=models.FloatField(default=100.0),
        ),
    ]
