# Generated by Django 4.2.9 on 2025-04-24 02:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itServ', '0023_societe_rayon_acceptable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='societe',
            options={'verbose_name': 'Société', 'verbose_name_plural': 'Sociétés'},
        ),
        migrations.RemoveField(
            model_name='societe',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='location_societe',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='rayon_acceptable',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='profil',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='profil',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='profil',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AddField(
            model_name='profil',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='itServ.societe', verbose_name='Entreprise'),
        ),
        migrations.AddField(
            model_name='societe',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='societe',
            name='date_maj',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AddField(
            model_name='societe',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='societe',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='societe',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_societes', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adresse',
            field=models.TextField(verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='poste',
            field=models.CharField(choices=[('EMPLOYE', 'Employé'), ('ResponsableRH', 'Responsable RH'), ('admin', 'Admin')], max_length=20, verbose_name='Poste'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='prenom',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='telephone',
            field=models.CharField(max_length=10, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='societe',
            name='adresse',
            field=models.TextField(default=datetime.datetime(2025, 4, 24, 2, 23, 48, 461325, tzinfo=datetime.timezone.utc), verbose_name='Adresse'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='societe',
            name='nom',
            field=models.CharField(max_length=100, verbose_name="Nom de l'entreprise"),
        ),
    ]
