# Generated by Django 4.2.9 on 2025-04-24 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itServ', '0024_alter_societe_options_remove_societe_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='societe',
            options={},
        ),
        migrations.RemoveField(
            model_name='profil',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='societe',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='date_maj',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='societe',
            name='modified_by',
        ),
        migrations.AddField(
            model_name='societe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 24, 2, 45, 7, 687648, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='societe',
            name='location_societe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='societe',
            name='rayon_acceptable',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='societe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='adresse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='poste',
            field=models.CharField(choices=[('EMPLOYE', 'Employé'), ('ResponsableRH', 'Responsable RH'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profil',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='societe',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='societe',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
