# Generated by Django 4.2.9 on 2025-04-25 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itServ', '0025_alter_societe_options_remove_profil_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itServ.societe', verbose_name='Entreprise'),
        ),
    ]
